/**
* The MIT License (MIT)
*
* Copyright (c) 2013 Daniel Wyatt
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
**/

#ifndef HIDKEYS_H
#define HIDKEYS_H

//HID key code usage IDs
enum {
  KEYBOARD_A  = 0x04,
  KEYBOARD_B,
  KEYBOARD_C,
  KEYBOARD_D,
  KEYBOARD_E,
  KEYBOARD_F,
  KEYBOARD_G,
  KEYBOARD_H,
  KEYBOARD_I,
  KEYBOARD_J,
  KEYBOARD_K,
  KEYBOARD_L,
  KEYBOARD_M,
  KEYBOARD_N,
  KEYBOARD_O,
  KEYBOARD_P,
  KEYBOARD_Q,
  KEYBOARD_R,
  KEYBOARD_S,
  KEYBOARD_T,
  KEYBOARD_U,
  KEYBOARD_V,
  KEYBOARD_W,
  KEYBOARD_X,
  KEYBOARD_Y,
  KEYBOARD_Z,
  KEYBOARD_1,
  KEYBOARD_2,
  KEYBOARD_3,
  KEYBOARD_4,
  KEYBOARD_5,
  KEYBOARD_6,
  KEYBOARD_7,
  KEYBOARD_8,
  KEYBOARD_9,
  KEYBOARD_0,
  KEYBOARD_ENTER,
  KEYBOARD_ESCAPE,
  KEYBOARD_BACKSPACE,
  KEYBOARD_TAB,
  KEYBOARD_SPACEBAR,
  //skip
  KEYBOARD_CAPS_LOCK = 0x39,
  KEYBOARD_F1,
  KEYBOARD_F2,
  KEYBOARD_F3,
  KEYBOARD_F4,
  KEYBOARD_F5,
  KEYBOARD_F6,
  KEYBOARD_F7,
  KEYBOARD_F8,
  KEYBOARD_F9,
  KEYBOARD_F10,
  KEYBOARD_F11,
  KEYBOARD_F12,
  KEYBOARD_PRINT_SCREEN,
  KEYBOARD_SCROLL_LOCK,
  KEYBOARD_PAUSE,
  KEYBOARD_INSERT,
  KEYBOARD_HOME,
  KEYBOARD_PAGE_UP,
  KEYBOARD_DELETE,
  KEYBOARD_END,
  KEYBOARD_PAGE_DOWN,
  KEYBOARD_RIGHT_ARROW,
  KEYBOARD_LEFT_ARROW,
  KEYBOARD_DOWN_ARROW,
  KEYBOARD_UP_ARROW,
  //skip
  KEYPAD_ENTER = 0x58,
  KEYPAD_1,
  KEYPAD_2,
  KEYPAD_3,
  KEYPAD_4,
  KEYPAD_5,
  KEYPAD_6,
  KEYPAD_7,
  KEYPAD_8,
  KEYPAD_9,
  KEYPAD_0,
  //skip
  KEYBOARD_F13 = 0x68,
  KEYBOARD_F14,
  KEYBOARD_F15,
  KEYBOARD_F16,
  KEYBOARD_F17,
  KEYBOARD_F18,
  KEYBOARD_F19,
  KEYBOARD_F20,
  KEYBOARD_F21,
  KEYBOARD_F22,
  KEYBOARD_F23,
  KEYBOARD_F24,
};

#endif

